Python 3.10 Update (#11216)
* Update pyside2 package and deprecated message
* Update pytest and pybind versions
* Fix python 3.10 where subprocess.run is outputing its --help argument result from calling SerializeContextTools to stderr instead of stdout, even though the result code is zero
* Fix error from PythonProxyObject with PyBind11 update to 2.7.1 that results in an 'unhashable type' for PythonProxyObject.
(See https://github.com/pybind/pybind11/pull/2291 )
* Fix deprecations errors caused be direct construction of EditorTestClass
* Fix crash caused by calling trying to access 'PyErr_Occurred' after pybind11::finalize_interpreter.
"Shut down the Python interpreter. No pybind11 or CPython API functions can be called after this. In addition, pybind11 objects must not outlive the interpreter:"
* Fix crash caused by calling trying to access 'PyErr_Occurred' after pybind11::finalize_interpreter.
    According to  https://pybind11.readthedocs.io/en/stable/reference.html :
    "Shut down the Python interpreter. No pybind11 or CPython API functions can be called after this. In addition, pybind11 objects must not outlive the interpreter:"
* Fix unit test that expected an unknown result from a crash, but is actually receiving a fail result
* Updates to support Python 3.10 on Linux
* Update versions in cmake scripts to 3.10.5
* Update 3rd Party Package References to python 3.10.5 related dependencies (pybind11, pyside2)
* Update PythonLoader_Linux to support new version
* Add PythonLoader instance to PythonSystemComponent to load/unload python3.10.5.so properly to fix new 3.8+ issue with undefined symbols (see https://docs.python.org/3/whatsnew/3.8.html#changes-in-the-c-api)
* Fix python 3.10 syntax error (using 'is' instead of '==' for an integer comparison)
* Minor hack for 'test_single_crash_test' to resolve an assertion based on the expected result type
* Update linux package hash for OpenImageIO / OpenColorIO
* Add Pyside2::Tools dependency for QtForPython
* Replace hard coded python shared library name with one that is extracted from the python library target
* Cleanup norecursedirs in pytest.ini
* Fix mac compile error :

Users/spham/github/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp:53:44: error: no viable conversion from 'optional<reference_wrapper<AzToolsFramework::Prefab::Instance>>' to 'optional<reference_wrapper<const AzToolsFramework::Prefab::Instance>>'
            InstanceOptionalConstReference focusedInstance = prefabFocusInterface->GetFocusedPrefabInstance(s_editorEntityContextId);
                                           ^
* Replace hardcoded python major/minor version number strings with a define passed in based on LY_PYTHON_VERSION_MAJOR_MINOR defined in LYPython.cmake
* Replace StringFunc::Path with AZ::IO::FixedPath to retrieve the filename from a path
* Applying suggestion from PR comments on reporting the state of a stoppython call

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>